res2 = C._update_parameters(1.0, 0.5, 0, 1, np.array([[1.0, 0.3], [0.3, 1.0]]), np.array([-1, +1]), np.array([0.4, -0.5]), 1.2, 0.1)
res3 = C._update_parameters(1.0, 2.0, 0, 1, np.array([[1.0, 0.3], [0.3, 1.0]]), np.array([-1, +1]), np.array([0.4, -0.5]), 1.2, 0.1)

res2:
(array([ 0.9,  0. ]), 1.95, 1)

res3:
(array([ 0.9,  0. ]), 2.7000000000000002, 1)

#self.assertTrue((np.allclose(res2[0], [0.1, -0.8]) and
#                 np.allclose(res2[1], 2.41, atol=1e-3) and
#                 np.allclose(res3[0], [0.9, 0.0]) and
#                 np.allclose(res3[1], 2.7, atol=1e-3)),
#                msg='_update_parameters: Error found.')